workflows:
  macos-build:
    name: macOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Install CocoaPods
        script: |
          cd macos
          pod install
      - name: Build macOS
        script: flutter build macos --release
    artifacts:
      - build/macos/Build/Products/Release/*.app
      - build/macos/Build/Products/Release/*.dmg