// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1DymQ6sLsFcAm58KylbnK0Ff4OqJuDak',
    appId: '1:401542905433:web:98495911d484f3cebebb48',
    messagingSenderId: '401542905433',
    projectId: 'csc339proj',
    authDomain: 'csc339proj.firebaseapp.com',
    storageBucket: 'csc339proj.firebasestorage.app',
    measurementId: 'G-R091LLR4Z2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv6emLS9dBTuXDZF8UJuc8rXGJDZJbJHo',
    appId: '1:401542905433:android:563af6b5ea1432ffbebb48',
    messagingSenderId: '401542905433',
    projectId: 'csc339proj',
    storageBucket: 'csc339proj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQp5BHfVH6aBiBPsQMsrgMC0Kkdwc4nik',
    appId: '1:401542905433:ios:e6d04c2f763674c6bebb48',
    messagingSenderId: '401542905433',
    projectId: 'csc339proj',
    storageBucket: 'csc339proj.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQp5BHfVH6aBiBPsQMsrgMC0Kkdwc4nik',
    appId: '1:401542905433:ios:e6d04c2f763674c6bebb48',
    messagingSenderId: '401542905433',
    projectId: 'csc339proj',
    storageBucket: 'csc339proj.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1DymQ6sLsFcAm58KylbnK0Ff4OqJuDak',
    appId: '1:401542905433:web:341a1333a908d5bfbebb48',
    messagingSenderId: '401542905433',
    projectId: 'csc339proj',
    authDomain: 'csc339proj.firebaseapp.com',
    storageBucket: 'csc339proj.firebasestorage.app',
    measurementId: 'G-11NG55BQFE',
  );
}
